variable "aws_region" {}
variable "tfe_instance_class" {}
variable "db_instance_class" {}
variable "redis_node_type" {}
variable "hosted_zone_name" {}
variable "tfe_license" {}
variable "tfe_http_port" {}
variable "tfe_https_port" {}
variable "tfe_encryption_password" {}
variable "tfe_version_image" {}
variable "tfe_host_path_to_certificates" {}
variable "lets_encrypt_cert" {}
variable "lets_encrypt_key" {}
variable "tfe_database_user" {}
variable "tfe_database_name" {}
variable "tfe_database_password" {}
variable "tfe_admin_user" {}
variable "tfe_admin_password" {}
variable "tfe_admin_email" {}
variable "tfe_org_name" {}
variable "tfe_workspace_name" {}
